riperiperi/FreeSO

Charvatia/Charvatia/App.config, Charvatia/Charvatia/CVMInstance.cs, Charvatia/Charvatia/Charvatia.sln, Charvatia/Charvatia/Properties/Settings.Designer.cs, Charvatia/Charvatia/Properties/Settings.settings
Makes it easier to test different debug lots from the server. Also is TargaImage was also missing from the solution. Is this still needed? I see it's still in FSO.Files still.
=> Added Debug Lot setting

TSOClient/tso.client/UI/Panels/UILiveMode.cs, TSOClient/tso.client/UI/Screens/CoreGameScreen.cs
Should check why ucp selectedavatar is not working, maybe becuase sim is created by net command
=> Added ui panel thunbmail button

TSOClient/tso.client/Content/Objects/catalog_downloads.xml, TSOClient/tso.client/UI/Controls/Catalog/UICatalog.cs, TSOClient/tso.content/WorldObjectCatalog.cs
Included into Content and UI Code
=> Add custom objects to catalog

TSOClient/FSO.Common.Domain/Shards/ClientShards.cs, TSOClient/FSO.Common.Domain/Shards/IShardsDomain.cs, TSOClient/FSO.Server.DataService/Providers/Client/ClientLotProvider.cs, TSOClient/FSO.Server.Database/DA/Avatars/DbAvatarSummary.cs, TSOClient/FSO.Server.Database/DA/Avatars/IAvatars.cs, TSOClient/FSO.Server.Database/DA/Avatars/SqlAvatars.cs, TSOClient/FSO.Server.Database/FSO.Server.Database.csproj, TSOClient/FSO.Server.Protocol/CitySelector/AvatarData.cs, TSOClient/FSO.Server/Domain/Shards.cs, TSOClient/FSO.Server/Servers/Api/Controllers/CitySelectorController.cs, TSOClient/tso.client/Controllers/LoadingScreenController.cs, TSOClient/tso.client/Controllers/PersonSelectionController.cs, TSOClient/tso.client/Controllers/PersonSelectionEditController.cs, TSOClient/tso.client/FSO.Client.csproj, TSOClient/tso.client/GameContent/CacheModule.cs, TSOClient/tso.client/GameController.cs, TSOClient/tso.client/Regulators/CityConnectionRegulator.cs, TSOClient/tso.client/Regulators/LotConnectionRegulator.cs, TSOClient/tso.client/TSOGame.cs, TSOClient/tso.client/UI/Controls/UILabel.cs, TSOClient/tso.client/UI/Panels/UIBuyMode.cs, TSOClient/tso.client/UI/Screens/PersonSelection.cs, TSOClient/tso.common/FSO.Common.csproj, TSOClient/tso.common/utils/Cache/CacheKey.cs, TSOClient/tso.common/utils/Cache/FileSystemCache.cs, TSOClient/tso.common/utils/Cache/ICache.cs, TSOClient/tso.content/ContentPreloader.cs
Ability to connect directly to a lot from SAS. House thumbnails also cache locally and are used for SAS.
=> House button in SAS

TSOClient/tso.client/FSO.Client.csproj, TSOClient/tso.client/UI/Controls/UITextEdit.cs, TSOClient/tso.client/UI/Framework/Parser/UIScript.cs, TSOClient/tso.client/UI/Framework/UIDebounce.cs, TSOClient/tso.client/UI/Framework/UIElement.cs, TSOClient/tso.client/UI/Panels/EODs/Archetypes/UIBasicEOD.cs, TSOClient/tso.client/UI/Panels/EODs/UIEODController.cs, TSOClient/tso.client/UI/Panels/EODs/UIScoreboardEOD.cs, TSOClient/tso.simantics/FSO.SimAntics.csproj, TSOClient/tso.simantics/NetPlay/EODs/Archetypes/VMBasicEOD.cs, TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODScoreboardPlugin.cs, TSOClient/tso.simantics/NetPlay/EODs/Utils/EODPersist.cs, TSOClient/tso.simantics/NetPlay/EODs/VMEODServer.cs
Continuing through the list of EODs. Still trying to make each one easier to build by adding archetypes and utilities.
This implements the scoreboard + some utilities for similar EOD types.
=> EOD: Scoreboard

TSOClient/tso.client/UI/Screens/CoreGameScreen.cs
=> City screen: resize mouse hit area on window resize

TSOClient/tso.client/UI/Panels/EODs/UIEODController.cs, TSOClient/tso.client/UI/Panels/EODs/UITrunkEOD.cs, TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODTrunkPlugin.cs, TSOClient/tso.simantics/NetPlay/EODs/VMEODServer.cs
All 9 costume trunk objects now work. Simple as that.
The only known issue is that the rummage loop animation set to run in the background does not work.
=> TrunkEOD: Done

TSOClient/tso.client/FSO.Client.csproj, TSOClient/tso.client/UI/Panels/EODs/UIEODController.cs, TSOClient/tso.client/UI/Panels/EODs/UITimerPluginEOD.cs, TSOClient/tso.simantics/FSO.SimAntics.csproj, TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODTimerPlugin.cs, TSOClient/tso.simantics/NetPlay/EODs/VMEODServer.cs
=> New EOD: Timer

TSOClient/tso.client/FSO.Client.csproj, TSOClient/tso.client/UI/Panels/EODs/UIBandEOD.cs, TSOClient/tso.client/UI/Panels/EODs/UIEODController.cs, TSOClient/tso.client/UI/Panels/EODs/Utils/UIEODLobby.cs, TSOClient/tso.simantics/FSO.SimAntics.csproj, TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODBandPlugin.cs, TSOClient/tso.simantics/NetPlay/EODs/VMEODServer.cs
To give you the maximum time needed to review and commit this code, I'll
spare you the details!
Suffice to say there are some UI changes I'd like to make to clean it
up.  But it's funcational and ready for test.  I hope I've made enough
checks against race issues.
=> New EOD: Band

TSOClient/tso.client/UI/Panels/EODs/UIBandEOD.cs, TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODBandPlugin.cs
Clients now see and hear the notes played by other players + 2 minor UI
bug fixes.
=> Band EOD: Bug fix

TSOClient/tso.simantics/FSO.SimAntics.csproj, TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODGameCompDrawACardPlugin.cs, TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODWarGamePlugin.cs
Fixed logic error for determining winner.
=> EOD: WarGame bug fix

TSOClient/FSO.Server/Servers/Lot/Domain/LotContainer.cs, TSOClient/tso.simantics/entities/VMAvatar.cs, TSOClient/tso.simantics/primitives/VMRefresh.cs
- Fix crippling lag caused by unleashed or dirty objects (mostly
affected store lots)
- Fix "expected events" misbehaving when running animations backwards.
(dresser animation)
- Fix OOW controller objects list not being respected.
=> [VM, Server] Minor fixes

TSOClient/tso.client/UI/Panels/UISandboxSelector.cs
Added option to load iff houses if TS1Hybrid  path exists.
=> Try to load iff houses into sandbox mode

TSOClient/FSO.Server.Api/Api.cs, TSOClient/FSO.Server.Api/App_Start/WebApiConfig.cs, TSOClient/FSO.Server.Api/Controllers/Admin/AdminUsersController.cs, TSOClient/FSO.Server.Api/Controllers/AuthLoginController.cs, TSOClient/FSO.Server/Servers/UserApi/UserApi.cs, TSOClient/FSO.Server/ToolRunServer.cs
- Make the API able to ban users and disconnect them.
- Show the INV-150 banned message instead of INV-110 message when a banned user tries to login.
=> [Server] Allow users to be banned from admin API

TSOClient/tso.client/UI/Panels/UIUCP.cs
There is no reason to my understanding why these should not work in 3D.
=> Fixes 3D shortcut limitations

TSOClient/FSO.UI/Controls/UIButton.cs, TSOClient/tso.client/UI/Panels/UIPieMenu.cs
My C# is not the best but, thought i'd make a small contribution anyways
=> Makes Sim's head look at Pie Menu Buttons

TSOClient/FSO.Common.Domain/Realestate/RealestateDomain.cs, TSOClient/tso.client/UI/Panels/UILotPurchaseDialog.cs
simplified number validation
made "|" a special character
fixed "too many apostrophes/dashes" bug
=> Lot naming fixes

TSOClient/tso.client/UI/Profile/UIJobInfo.cs
During testing, I was never able to get the dancer job so that makes sense why this never got properly tested.
=> Fixing JobUI for Dancer Job, some how this fell through the cracks.

TSOClient/tso.simantics/VM.cs
=> [Fix4simitone] I want to sit on The Polar Bear Rug!

TSOClient/tso.simantics/utils/VMTS1Activator.cs
=> [Fix for Simitone] Some objects are gone.

TSOClient/FSO.Server.Api.Core/Controllers/AvatarInfoController.cs, TSOClient/FSO.Server.Api.Core/Controllers/BulletinInfoController.cs, TSOClient/FSO.Server.Api.Core/Controllers/ElectionInfoController.cs, TSOClient/FSO.Server.Api.Core/Controllers/LotInfoController.cs, TSOClient/FSO.Server.Api.Core/Controllers/NhoodInfoController.cs, TSOClient/FSO.Server.Database/DA/AvatarClaims/DbAvatarClaim.cs, TSOClient/FSO.Server.Database/DA/AvatarClaims/IAvatarClaims.cs, TSOClient/FSO.Server.Database/DA/AvatarClaims/SqlAvatarClaims.cs, TSOClient/FSO.Server.Database/DA/LotClaims/DbLotClaim.cs, TSOClient/FSO.Server.Database/DA/LotClaims/ILotClaims.cs, TSOClient/FSO.Server.Database/DA/LotClaims/SqlLotsClaims.cs, TSOClient/FSO.Server.Database/DA/LotTop100/ILotTop100.cs, TSOClient/FSO.Server.Database/DA/LotTop100/SqlLotTop100.cs
New API calls for
- Avatar info
- Lot info
- Neighborhood info
- Bulletin info
- Election info
=> Added new API functionalities

TSOClient/tso.client/UI/Panels/UISetupBackground.cs
- If there is a directory called "Content/SplashScreens", the game will use a random PNG image from that directory.
- The file "Content/setup.png" still works as an alternative should this directory not exist or be empty.
=> Random splash screen

TSOClient/tso.simantics/Engine/VMSuitProvider.cs
- Fixing Outfits for DJ and Dancer Job per [TSOMania](https://www.tsomania.net/gameguides/jobs_dj_levels.php)
- Fixing equation for determining 'level' which is what is used for determining which array element of a job outfit to select, see pull request for tabled fix data points and what this changes.
- Fixed a MIN value situation, where the value should never become 3, because 3 would be index out of bounds.
Below I have put together a table, that represents the current values, and the goal values. Job Grade is the current int of job. Expected result column built based on TSOMania game guide, the current computed C# value without round, and the tested C# value with round (the fix), and finally just a confirmation column, on observing the current values using Volcanic.
|   JOB GRADE  | …
=> Fixes for DJ/Dancer Job Outfits and Fixes for All Outfits for all jobs.
