riperiperi/FreeSO

.gitignore
TSOClient/FSO.Server/Servers/City/Domain/LotServerPicker.cs
TSOClient/FSO.Server/Servers/Lot/Domain/LotContainer.cs
TSOClient/FSO.Server/Servers/Lot/Domain/LotHost.cs
TSOClient/FSO.Server/Servers/Lot/Lifecycle/CityConnections.cs
TSOClient/FSO.Server/Servers/Lot/LotServer.cs

* Lot servers detect city disconnects and save / shutdown lots
* CityServers now reconnects after a city goes down. This means you can reboot a city without having to reboot the lot servers.
* LotAllocations can now handle a city reconnecting
* Lot servers now release lot locks on shutdown as well as city for cases where the city is offline
* Main thread is no longer shutdown after 4 background loops without tasks. When shutting down no background tasks are generated. If save takes a while this interrupts the save process.
* Bunch of error catches

Lot servers handle city disconnects with more grace

---

TSOClient/tso.client/UI/Controls/UIAlert.cs
TSOClient/tso.client/UI/Controls/UITextBox.cs
TSOClient/tso.client/UI/Panels/EODs/UIAbstractRackEOD.cs
TSOClient/tso.client/UI/Panels/EODs/UIPermissionDoorEOD.cs
TSOClient/tso.client/UI/Panels/EODs/UIRackOwnerEOD.cs
TSOClient/tso.client/UI/Panels/EODs/UISlotsEOD.cs
TSOClient/tso.client/UI/Panels/EODs/UITrunkEOD.cs
TSOClient/tso.simantics/FSO.SimAntics.csproj
TSOClient/tso.simantics/NetPlay/EODs/Handlers/Data/VMEODRackData.cs
TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMAbstractEODRackPlugin.cs
TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODRackOwnerPlugin.cs

•Rack owners can name their racks, and the name is saved on the server and loaded by the next user, customer or owner.
•Only 32 characters are allowed for rack names.
•A couple more Parse methods were replaced with TryParse for safety.
•A few additional checks were made to functions to ensure the calling clients belong to the rack owner
•MaxChars was added to Alert Options
•UITextEdit MaxChars functionality was copied into UITextBox
•Doors and Slots EOD now limit the number of characters the users can enter into the alert.

Rack Owners can now name their racks & Other UI polishing tweaks

---

TSOClient/FSO.UI/Controls/UITextEdit.cs
TSOClient/tso.client/UI/Panels/UILoginDialog.cs
TSOClient/tso.client/UI/Screens/LoginScreen.cs

This PR adjusts the workflow for an incorrect password, giving a better User Experience for users that mistype their passwords, further more, it helps users return to re-enter their password and allows adjustments for incorrectly typed usernames with a Shift + Tab functionality. This PR also adjusts the password workflow such that it no longer spams the login services with incorrect credentials when users press enter again after the wrong credentials are provided.
Commonly users mistype their password, especially if the passwords are "secure", sometimes fat-fingers happen. (I'll admit I enter my password wrong quite commonly into FreeSO for some reason).
Further more, the way the dialog system was presenting the error messages was on top of the UILoginScreen, so every time a user pressed …

Better User Experience for Login Workflow.

---

TSOClient/tso.client/UI/Panels/UIChatPanel.cs
TSOClient/tso.client/UI/Panels/UILotControl.cs
TSOClient/tso.client/UI/Panels/UIUCP.cs
TSOClient/tso.client/UI/Screens/CoreGameScreen.cs

- Shortcut keys added:
- F1 - Live Mode
- F2 - Buy Mode
- F3 - Build Mode
- F4 - Property Mode
- F5 - Options
- +/- - Zooms view in/out (2D & 3D)
- </> - Rotates view left/right (2D & 3D)
- Home/End - Steps walls up/down
- Page Up/Down - Ascends/descends the active floor
- WASD/Arrow Keys - Pans the camera (2D & 3D)
- CTRL+F1 - Toggles the debug menu (This was changed to prevent conflicts with the Live Mode shortcut key)
- Chatbox changes
- The chatbox will now automatically focus when it is opened.
- Pressing Enter in the chatbox with an empty message will toggle its focus.
- Pressing ESC while the chatbox is focused will erase any message being typed.
- Pressing ESC while the chatbox is focused with an empty message will remove its focus.

Basic shortcut key functionality. Minor chatbox changes

---

TSOClient/tso.common/IniConfig.cs

Fixes the issue with default config values that contain decimals (floats, decimals, doubles). It should also update accordingly if a user should ever switch their number separator format.

Fix decimal numbers for different User Culture settings

---

TSOClient/FSO.UI/Controls/UIProgressBar.cs
TSOClient/tso.client/FSO.Client.csproj
TSOClient/tso.client/FSOFacade.cs
TSOClient/tso.client/UI/Panels/UILotControl.cs
TSOClient/tso.client/UI/Panels/UIPersonPage.cs
TSOClient/tso.client/UI/Profile/UIJobInfo.cs
TSOClient/tso.simantics/primitives/VMDialogPrivateStrings.cs

This PR adds a new UIJobInfo class that is able to take in variables from both the UIPersonPage and UILotControl (Job Grade [Level], Job Type, and Total Cumulative Experience Points), and display a nicer looking UI and provide some additional information that is helpful as you progress through your job. The two new bits of information is what you current job level is, and your performance, which is a progress bar, that gives you a % till promotion.
These changes have been extensively tested on all the current job career paths and tested on various roll overs from one grade to another.
This is my first UI element addition to FreeSO, so I did my best to make it look as nice as I could, and match the required look and feel of FreeSO / TSO. Please let me know here if you have any additional …

New Jobs UIJobInfo Dialog / Alert

---

TSOClient/tso.client/UI/Panels/UIAsyncPriceDialog.cs
TSOClient/tso.client/UI/Panels/UIObjectHolder.cs

This change prevents a player from accidentally deleting an item when setting the SalePrice via the delete key.
Most people are familiar with using a combination of delete and backspace in-order to edit text in a textfield, this will prevent the accident that everyone has done at least once, of pressing delete and selling a very expensive item.
Additionally one very small UI/UX enhancement was made, in that when you select "Set for Sale", and the dialog is presented, your cursor is automatically focused in and ready to adjust the price.
Implementation: I actually really thought about the best way to take care of this situation. My initial implementation used on focus events to track the dialog and the focus of the ForSalePrice UITextEdit. But in the end I wanted to make sure that the …

Fixing Accidental Sale from Price Dialog

---

TSOClient/tso.client/UI/Panels/UILotControl.cs
TSOClient/tso.client/UI/Profile/UIJobInfo.cs

Fixing two bugs that were discovered in #bug-reports:
- Max Level players crash when looking at their job history, due to the progress bar not being allocated for them and it blowing up on the `destroy()`
- Telephone users with multiple jobs are getting unexpected job results. Switching the logic over `GetPersonData` is more reliable and follows similar paradigms of other controllers.
- Minor commented out code clean-up that was missed previously.
Sorry for the bugs!

[Bug Fixes] JobUI Crashes and Unreliable Phone Results

---

TSOClient/tso.client/UI/Panels/UIObjectHolder.cs

Uses previously existing function which checks:
- Is your focus currently in another textbox? (Previous Deletion Commit Addition)
- Are you holding it?
- Do you own it?
- Can you delete it?
Tested in Sandbox, works well !

Press I to inventory an item, while it's being held.

---

TSOClient/FSO.Server.Api.Core/Controllers/AvatarInfoController.cs
TSOClient/FSO.Server.Api.Core/Controllers/LotInfoController.cs
TSOClient/FSO.Server.Api.Core/Controllers/UserOAuthController.cs
TSOClient/FSO.Server.Database/DA/AvatarClaims/IAvatarClaims.cs
TSOClient/FSO.Server.Database/DA/AvatarClaims/SqlAvatarClaims.cs
TSOClient/FSO.Server.Database/DA/Avatars/IAvatars.cs
TSOClient/FSO.Server.Database/DA/Avatars/SqlAvatars.cs
TSOClient/FSO.Server.Database/DA/LotClaims/DbLotClaim.cs
TSOClient/FSO.Server.Database/DA/Lots/ILots.cs
TSOClient/FSO.Server.Database/DA/Lots/SqlLots.cs

- userOauth token (with specified permissions)
- avatarinfo
get avatars from specific user (req user auth)
get avatars from multiple ids
get all avatars now can get up to 500 avatars per page
getting all neighborhood avatars is more efficient
online avatars can also be requested as compact now (only online count)
- lotinfo
json objects now include lot_id (more consistent/reliable value than location)
json objects now include admit_mode
get lots from multiple ids
online lots can also be requested as compact now (only online count)
added funtion for getting all the lots by pages, and max 500 lots per page

[API] Added funtionality and efficiency

---

TSOClient/tso.common/rendering/framework/io/InputManager.cs

A makeshift solution to #155 – AFAIK, you cannot catch the difference between `LeftCtrl`+`RightAlt` and `RightAlt`.

Makeshift fix for AltGr treated as Ctrl

---

TSOClient/tso.client/UI/Panels/UILotControl.cs
TSOClient/tso.client/UI/Panels/UIObjectHolder.cs
TSOClient/tso.client/UI/Panels/UIUCP.cs
TSOClient/tso.client/UI/Screens/SandboxGameScreen.cs
TSOClient/tso.common/rendering/framework/io/InputManager.cs
TSOClient/tso.common/rendering/framework/model/UpdateState.cs

The game should no longer capture keyboard keys while the window is out of focus. A lot/facade cannot be saved while an input is in focus.
AltGr is no longer treated as Ctrl… but, unfortunately, Ctrl isn't detected in `AltGr`+`LeftCtrl`. It's a makeshift solution, like #156.

No out-of-window keys capturing, AltGr ≠ Ctrl (continued)

---

TSOClient/tso.client/UI/Panels/UIChatBalloon.cs

This will make the UIChatBalloon for an admin/moderator sim appear red instead of blue to stand out among users. It checks if the avatar's TSOState permissions attribute is set to Admin when the balloon text is updated. To maintain user customization settings, this does not have an impact on the chat text color of the balloon, but white is the easiest color to read in my opinion.

Admin Red Chat Balloon

---

TSOClient/tso.client/Controllers/Panels/BookmarksController.cs

The bookmarks panel does not refresh states of bookmarked players as long as you don't click another tab. This is an attempt to fix that minor issue.

Refresh bookmarks panel everytime it shows

---

TSOClient/tso.client/UI/Panels/EODs/UIRackEOD.cs
TSOClient/tso.simantics/NetPlay/EODs/Handlers/VMEODRackPlugin.cs

- When attempting to buy an outfit a Sim already owned, the transaction no longer silently fails _without_ charging the Sim's budget. An error message is displayed alerting the player.
- When attempting to buy an outfit in a category in which a Sim already owns 5 outfits, the transaction no longer silently fails _after_ charging a Sim's budget. An error message is displayed alerting the player and money is not deducted from the budget.
Rather than creating a new .cst entry for the "You cannot buy the same outfit twice" case, I just repeated the "You have no more room in your backpack" message.

RackEOD: Bug fixes

---

TSOClient/FSO.IDE/EditorComponent/Primitives/SetToNextDescriptor.cs
TSOClient/FSO.SimAntics.JIT/Translation/CSharp/Primitives/CSSetToNextPrimitive.cs
TSOClient/tso.simantics/Model/VMObjectQueries.cs
TSOClient/tso.simantics/Primitives/VMSetToNext.cs

The primitive Set To Next allows for a new operator called "object with same semiglobal as", which iterates through any object whose semiglobal is shared with the object type that has been chosen.

Set to Next primitive operator "object with same semiglobal as"

---

TSOClient/tso.client/UI/Panels/UISetupBackground.cs

I recently started working with the repo and saw that this throws an Exception on a clean repo install, apparently this folder is optional but its DirectoryException is not handled.

Handle DirectoryNotFoundException if the SplashScreens directory does not exist

---

TSOClient/tso.client/UI/Panels/UIPieMenu.cs

Pie menu no longer displays 1 frame of the background at full size before resizing. The Image component considers Width/Height==0 to mean don't scale the image at all (has no way to represent unset/null). Instead of changing the image component and risking breaking other usages this just starts the background at 2x2.

fix: pie menu no longer glitches for 1 frame.

---

TSOClient/tso.client/Rendering/City/CityGeometry.cs
TSOClient/tso.simantics/Entities/VMAvatar.cs
TSOClient/tso.simantics/Entities/VMEntity.cs

Adds specific code for panning entity sounds while in 3D mode, as previously the 2D code was used causing it to jump around and be inaccurate.
Avatars are also now added to the VM sound entities when they play a sound from an event, so that it pans around as you move the camera rather than staying in place.

[VM] 3D audio panning

---

TSOClient/FSO.IDE/EditorComponent/Commands/SetFirstCommand.cs
TSOClient/FSO.IDE/EditorComponent/EditorScope.cs
TSOClient/FSO.IDE/EditorComponent/VarSoundSelect.cs
TSOClient/FSO.IDE/EntityInspector.Designer.cs
TSOClient/FSO.IDE/EntityInspector.cs
TSOClient/FSO.IDE/MainWindow.Designer.cs
TSOClient/FSO.IDE/ResourceBrowser/IFFResComponent.cs
TSOClient/FSO.IDE/ResourceBrowser/IffNameDialog.cs
TSOClient/FSO.IDE/ResourceBrowser/OBJDEditor.cs
TSOClient/FSO.IDE/ResourceBrowser/OBJfEditor.cs
TSOClient/FSO.IDE/ResourceBrowser/ResourceEditors/BCONResourceControl.cs
TSOClient/FSO.IDE/ResourceBrowser/ResourceEditors/BHAVResourceControl.cs
TSOClient/FSO.IDE/ResourceBrowser/UpgradeEditor.cs
TSOClient/tso.client/UI/Panels/UIDebugMenu.cs

I've been using Volcanic a bunch these past few days and so I've implemented a number of fixes and changes to improve the experience a bit. 
I know it's kind of a big PR, sorry about that, so if there's anything that needs reverting, changing or anything please do let me know!
This is mostly fixes, quality of life changes and implementation of previously placeholder/stubbed features.
Full changelog:
**Fixes:**
- Fixed crash when attempting to save a .piff with added FWAVs/Sound Events.
- Fixed potential crash when attempting to save a .piff with regenerated catalog thumbnails.
- BHAV Editor: Set As First is now fully implemented and shouldn't cause any strange behavior.
- BHAV Editor: BCON Constants are now bounds checked, fixing an exception, and labeled.
**Features:**
- TPRP/Metadata …

Volcanic - Fixes and QoL changes.

---

TSOClient/tso.simantics/Model/VMGenericTSOCallMode.cs
TSOClient/tso.simantics/Primitives/VMGenericTSOCall.cs

+ Adds FSOIsStackObjectPendingRoommateDeletion: Returns true when the Stack Object is pending deletion after their owner moved out of the property.
+ Adds FSOIsStackObjectAllowedByLotCategory: Returns true if the Stack Object is allowed in the current lot category.

Disabled flags TSO Generic calls.

---

TSOClient/FSO.Server/Servers/Lot/Domain/LotContainer.cs

- For DJ / Dancer the `jobType` variable here is always 2 (it would be bad if it was greater than 2 because JobGradeToLotGroup[jobType] of anything beyond 2 isnt defined).
- So we can safely change this check to `jobType == 2` to ensure that DJ and Dancer jobs will have the opportunity to generate a random number either 1 or 2, instead of just 1.

Enable nightclub03_00 lot file based on jobType.

---

TSOClient/tso.common/Utils/TextureUtils.cs

Take average color, then use vector math to get the furthest color from the average, then again find the furthest color from the furthest color.

Improve extreme color calculation for DXT compress

---

Documentation/Building FreeSO.md

This PR updates the capitalization of the Protobuild.exe command in the documentation, making it easier to copy and paste directly instead of typing it myself from the screenshot :)

Correct capitalization for the Protobuild command in documentation
